POST http://localhost:3001/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc4MzQ3MzEsInN1YiI6IjJhZGQ4NmYxLTg4OGMtNDAxMy1hOTM1LTkwODlhMmE2NmRmZiJ9.R9K3nnPRLOdSpYtUxUlxjgv9Sn2R1x1sD6ahEB0t5pg

{
  "name": "My Product",
  "price": 100
}

###

GET http://localhost:3001/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc4MzQ3MzEsInN1YiI6IjJhZGQ4NmYxLTg4OGMtNDAxMy1hOTM1LTkwODlhMmE2NmRmZiJ9.R9K3nnPRLOdSpYtUxUlxjgv9Sn2R1x1sD6ahEB0t5pg

###

GET http://localhost:3001/products/a28756d6-8c4a-4935-84f3-936ef6afd688 HTTP/1.1

###

PUT http://localhost:3001/products/a28756d6-8c4a-4935-84f3-936ef6afd688 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc4MzQ3MzEsInN1YiI6IjJhZGQ4NmYxLTg4OGMtNDAxMy1hOTM1LTkwODlhMmE2NmRmZiJ9.R9K3nnPRLOdSpYtUxUlxjgv9Sn2R1x1sD6ahEB0t5pg

{
  "name": "My Product Updated",
  "price": 200
}

###

DELETE http://localhost:3001/products/a28756d6-8c4a-4935-84f3-936ef6afd688 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc4MzQ3MzEsInN1YiI6IjJhZGQ4NmYxLTg4OGMtNDAxMy1hOTM1LTkwODlhMmE2NmRmZiJ9.R9K3nnPRLOdSpYtUxUlxjgv9Sn2R1x1sD6ahEB0t5pg
